site_name: 重庆大学转专业完全指南
site_url: https://cqu-majorchange.top
site_author: line2345
site_description: 提供重庆大学各学院转专业政策、经验分享、历年数据分析及申请指南的综合信息平台

# 仓库
repo_name: cqu-majorchange
repo_url: https://github.com/line2345/cqu-majorchange

theme:
  name: material
  custom_dir: docs/overrides
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: 关闭自动模式
  #primary: blue grey
  - media: "(prefers-color-scheme: light)"
    scheme: default # 日间模式
    primary: teal # 上方的
    accent: green # 链接等可交互元件的高亮色
    # teal
    toggle:
      icon: material/toggle-switch # 图标
      name: 切换至夜间模式 # 鼠标悬浮提示
  - media: "(prefers-color-scheme: dark)"
    scheme: slate # 夜间模式
    primary: black
    accent: indigo
    # teal
    toggle:
      icon: material/toggle-switch-off-outline
      name: 切换至日间模式
  
  features:
    - navigation.top  # 启用顶部导航
    - navigation.tabs # 可选：如果有子级内容，可以将其显示为标签式导航
    - content.code.annotate  # 启用代码注释功能（未来可用）
    - content.tooltips  # 支持工具提示（如悬停说明）

# 导航页
nav:
  - 首页: index.md
  - 转专业指南: 
    - 0. 导航: majorchange/nav.md
    - 1. 前言: majorchange/1. 前言.md
    - 2. 流程概览: majorchange/2. 流程概览.md
    - 3. 转专业前的衡量: majorchange/3. 转专业前的衡量.md
    - 4. 准备工作与报名: majorchange/4. 报名与准备工作.md
    - 5. 面试与笔试: majorchange/5. 面试与笔试.md
    - 6. 转专业后的安排: majorchange/6. 转专业后的安排.md
    - 7. 学分认证与补课: majorchange/7. 学分认证与补课.md
    - 8. 保研相关: majorchange/8. 保研.md
    - 9. 经验分享: majorchange/9. 经验分享.md
    - 10. 参考资料: majorchange/10. 参考资料.md

markdown_extensions:
  - meta  # 启用元数据扩展
  - tables # 表格支持
  - pymdownx.arithmatex: # 数学库支持
      generic: true

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: false
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  comments: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/line2345
    - icon: fontawesome/solid/envelope
      link: mailto://476057016line@gmail.com
  analytics:
    provider: google
    property: UA-XXXXXXXX-X
  meta:
    keywords: 重庆大学, 转专业, 专业调整, 申请指南, 重大, CQU, 学院政策, 经验分享

plugins:
  - search
  - meta-descriptions


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # MathJax数学支持

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css # KaTeX数学支持
  - stylesheets/extra.css

